behaviors:
    Dog:
        trainer_type: ppo
        hyperparameters:
            batch_size: 500
            buffer_size: 50000
            num_epoch: 5
        network_settings:
            hidden_units: 512
            num_layers: 3
#            memory:
#                memory_size: 128
#                sequence_length: 8
        reward_signals:
            extrinsic:
                gamma: 0.99
                strength: 1.0
            curiosity:
                strength: 0.005
                gamma: 0.98
                encoding_size: 128
        time_horizon: 200
        max_steps: 1e7
        threaded: true
        summary_freq: 50000
        #checkpoint_interval: 40000
        keep_checkpoints: 100
engine_settings:
  width: 640
  height: 360